#############################################################################
# Generated by PAGE version 7.0
#  in conjunction with Tcl version 8.6
#  Jan 21, 2022 11:36:55 AM +0530  platform: Darwin
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m55" -background $vTcl(actual_gui_bg) \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 855x718+451+991
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1585 1746
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #d86025 \
        -compound left \
        -font {-family Verdana -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightcolor black -text {Message Decoder} 
    vTcl:DefineAlias "$top.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab52 \
        -foreground black -text {Select Signal File} \
        -background $vTcl(actual_gui_bg) -height 115 -highlightcolor black \
        -width 741 
    vTcl:DefineAlias "$top.lab52" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab52
    button $site_3_0.but53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Select File} 
    vTcl:DefineAlias "$site_3_0.but53" "btnSelectFile" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent54 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -show no -state readonly -width 686 
    vTcl:DefineAlias "$site_3_0.ent54" "txtFileName" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 0.013 -y 0 -rely 0.348 -width 101 \
        -relwidth 0 -height 52 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 0 -relx 0.153 -y 0 -rely 0.347 -width 686 \
        -relwidth 0 -height 50 -relheight 0 -anchor nw -bordermode ignore 
    menu $top.m55 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    labelframe $top.lab56 \
        -foreground black -text {Decoder Thresholds} \
        -background $vTcl(actual_gui_bg) -height 95 -highlightcolor black \
        -width 741 
    vTcl:DefineAlias "$top.lab56" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab56
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Preamble Threshold} 
    vTcl:DefineAlias "$site_3_0.lab57" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent59 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 126 
    vTcl:DefineAlias "$site_3_0.ent59" "txtPreambleThres" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Bit Decode Threshold} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent61 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 126 
    vTcl:DefineAlias "$site_3_0.ent61" "txtBitDecodeThres" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -state disabled -text {Decode Message} 
    vTcl:DefineAlias "$site_3_0.but62" "btnDecode" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.316 -width 0 \
        -relwidth 0.193 -height 0 -relheight 0.137 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent59 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.526 -width 130 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.324 -y 0 -rely 0.316 -width 0 \
        -relwidth 0.181 -height 0 -relheight 0.147 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent61 \
        -in $site_3_0 -x 0 -relx 0.324 -y 0 -rely 0.526 -width 130 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but62 \
        -in $site_3_0 -x 0 -relx 0.81 -y 0 -rely 0.421 -width 121 -relwidth 0 \
        -height 42 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab63 \
        -foreground black -text Output -background $vTcl(actual_gui_bg) \
        -height 316 -highlightcolor black -width 740 
    vTcl:DefineAlias "$top.lab63" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab63
    entry $site_3_0.ent65 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -state readonly -width 706 
    vTcl:DefineAlias "$site_3_0.ent65" "txtDecodeStatus" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_3_0.lab48 \
        -foreground black -text {Decoded Message} \
        -background $vTcl(actual_gui_bg) -height 209 -highlightcolor black \
        -width 783 
    vTcl:DefineAlias "$site_3_0.lab48" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab48
    label $site_4_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Select an EM trace file to start decoding...} 
    vTcl:DefineAlias "$site_4_0.lab50" "Label4" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab50 \
        -in $site_4_0 -x 0 -relx 0.026 -y 0 -rely 0.183 -width 0 \
        -relwidth 0.94 -height 0 -relheight 0.685 -anchor nw \
        -bordermode ignore 
    labelframe $site_3_0.lab49 \
        -foreground black -text {Decoder Status} \
        -background $vTcl(actual_gui_bg) -height 68 -highlightcolor black \
        -width 783 
    vTcl:DefineAlias "$site_3_0.lab49" "Labelframe5" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab49
    label $site_4_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Decoder ready select EM trace file to begin...} 
    vTcl:DefineAlias "$site_4_0.lab48" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor #000000 -text Label 
    vTcl:DefineAlias "$site_4_0.lab47" "Label6" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab48 \
        -in $site_4_0 -x 0 -relx 0.026 -y 0 -rely 0.294 -width 0 \
        -relwidth 0.428 -height 0 -relheight 0.588 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab47 \
        -in $site_4_0 -x 0 -relx 0.881 -y 0 -rely 0.324 -width 0 \
        -relwidth 0.111 -height 0 -relheight 0.588 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent65 \
        -in $site_3_0 -x 0 -relx 0.041 -y 0 -rely -0.175 -width 706 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.024 -y 0 -rely 0.33 -width 0 \
        -relwidth 0.948 -height 0 -relheight 0.628 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.024 -y 0 -rely 0.09 -width 0 \
        -relwidth 0.948 -height 0 -relheight 0.204 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab49 \
        -in $top -x -15 -y 0 -width 877 -relwidth 0 -height 95 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 15 -y 112 -width 826 -relwidth 0 -height 121 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 11 -y 253 -width 827 -relwidth 0 -height 100 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 11 -y 369 -width 826 -relwidth 0 -height 333 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

